// Generated by scripts/generate-locales.mjs.
import Page from "../download";
import { LocaleContext } from "../../../src/i18n/context";
export const frontmatter = {
  title: "Tải Dream",
  description: "Tải Dream cho macOS, Windows và Linux.",
  search: false,
};
export default function LocalizedPage() {
  return (
    <LocaleContext.Provider value="vi">
      <Page />
    </LocaleContext.Provider>
  );
}
