// Generated by scripts/generate-locales.mjs.
export { default } from "../download";
export const frontmatter = {
  title: "Tải Dream",
  description: "Tải Dream cho macOS, Windows và Linux.",
  search: false,
};
