// Generated by scripts/generate-locales.mjs.
export { default } from "../home";
export const frontmatter = {
  title: "Dream — IDE dành cho lập trình với AI",
  description:
    "Dream là IDE mã nguồn mở trên máy tính để làm việc với nhiều tác nhân lập trình AI.",
  search: false,
};
