// Generated by scripts/generate-locales.mjs.
import Page from "../home";
import { LocaleContext } from "../../../src/i18n/context";
export const frontmatter = {
  title: "Dream — IDE dành cho lập trình với AI",
  description:
    "Dream là IDE mã nguồn mở trên máy tính để làm việc với nhiều tác nhân lập trình AI.",
  search: false,
};
export default function LocalizedPage() {
  return (
    <LocaleContext.Provider value="vi">
      <Page />
    </LocaleContext.Provider>
  );
}
