// Generated by scripts/generate-locales.mjs.
import Page from "../download";
import { LocaleContext } from "../../../src/i18n/context";
export const frontmatter = {
  title: "下載 Dream",
  description: "下載適用於 macOS、Windows 和 Linux 的 Dream。",
  search: false,
};
export default function LocalizedPage() {
  return (
    <LocaleContext.Provider value="zh-Hant">
      <Page />
    </LocaleContext.Provider>
  );
}
