// Generated by scripts/generate-locales.mjs.
export { default } from "../download";
export const frontmatter = {
  title: "下載 Dream",
  description: "下載適用於 macOS、Windows 和 Linux 的 Dream。",
  search: false,
};
