// Generated by scripts/generate-locales.mjs.
export { default } from "../hello";
export const frontmatter = {
  title: "Dream — 專為 AI 程式開發打造的 IDE",
  description: "Dream 是一款開源桌面 IDE，讓你與多個 AI 程式開發代理協同工作。",
  search: false,
};
