// Generated by scripts/generate-locales.mjs.
export { default } from "../download";
export const frontmatter = {
  title: "Baixar Dream",
  description: "Baixe o Dream para macOS, Windows e Linux.",
  search: false,
};
