// Generated by scripts/generate-locales.mjs.
import Page from "../download";
import { LocaleContext } from "../../../src/i18n/context";
export const frontmatter = {
  title: "Baixar Dream",
  description: "Baixe o Dream para macOS, Windows e Linux.",
  search: false,
};
export default function LocalizedPage() {
  return (
    <LocaleContext.Provider value="pt">
      <Page />
    </LocaleContext.Provider>
  );
}
