// Generated by scripts/generate-locales.mjs.
import Page from "../hello";
import { LocaleContext } from "../../../src/i18n/context";
export const frontmatter = {
  title: "Dream — a IDE para programar com IA",
  description:
    "Dream é uma IDE de desktop de código aberto para trabalhar com vários agentes de programação com IA.",
  search: false,
};
export default function LocalizedPage() {
  return (
    <LocaleContext.Provider value="pt">
      <Page />
    </LocaleContext.Provider>
  );
}
