// Generated by scripts/generate-locales.mjs.
export { default } from "../home";
export const frontmatter = {
  title: "Dream — a IDE para programar com IA",
  description:
    "Dream é uma IDE de desktop de código aberto para trabalhar com vários agentes de programação com IA.",
  search: false,
};
