// Generated by scripts/generate-locales.mjs.
export { default } from "../download";
export const frontmatter = {
  title: "Dreamをダウンロード",
  description: "macOS、Windows、Linux向けのDreamをダウンロード。",
  search: false,
};
