// Generated by scripts/generate-locales.mjs.
export { default } from "../hello";
export const frontmatter = {
  title: "Dream — AIコーディングのためのIDE",
  description:
    "Dreamは、複数のAIコーディングエージェントと作業するためのオープンソースのデスクトップIDEです。",
  search: false,
};
