// Generated by scripts/generate-locales.mjs.
import Page from "../home";
import { LocaleContext } from "../../../src/i18n/context";
export const frontmatter = {
  title: "Dream — AIコーディングのためのIDE",
  description:
    "Dreamは、複数のAIコーディングエージェントと作業するためのオープンソースのデスクトップIDEです。",
  search: false,
};
export default function LocalizedPage() {
  return (
    <LocaleContext.Provider value="ja">
      <Page />
    </LocaleContext.Provider>
  );
}
