// Generated by scripts/generate-locales.mjs.
import Page from "../download";
import { LocaleContext } from "../../../src/i18n/context";
export const frontmatter = {
  title: "Dream herunterladen",
  description: "Lade Dream für macOS, Windows und Linux herunter.",
  search: false,
};
export default function LocalizedPage() {
  return (
    <LocaleContext.Provider value="de">
      <Page />
    </LocaleContext.Provider>
  );
}
