// Generated by scripts/generate-locales.mjs.
export { default } from "../download";
export const frontmatter = {
  title: "Dream herunterladen",
  description: "Lade Dream für macOS, Windows und Linux herunter.",
  search: false,
};
