// Generated by scripts/generate-locales.mjs.
import Page from "../home";
import { LocaleContext } from "../../../src/i18n/context";
export const frontmatter = {
  title: "Dream — die IDE für KI-gestütztes Programmieren",
  description:
    "Dream ist eine Open-Source-Desktop-IDE für die Arbeit mit mehreren KI-Programmieragenten.",
  search: false,
};
export default function LocalizedPage() {
  return (
    <LocaleContext.Provider value="de">
      <Page />
    </LocaleContext.Provider>
  );
}
