// Generated by scripts/generate-locales.mjs.
export { default } from "../home";
export const frontmatter = {
  title: "Dream — die IDE für KI-gestütztes Programmieren",
  description:
    "Dream ist eine Open-Source-Desktop-IDE für die Arbeit mit mehreren KI-Programmieragenten.",
  search: false,
};
