// Generated by scripts/generate-locales.mjs.
export { default } from "../download";
export const frontmatter = {
  title: "Dream 다운로드",
  description: "macOS, Windows, Linux용 Dream을 다운로드하세요.",
  search: false,
};
