// Generated by scripts/generate-locales.mjs.
import Page from "../download";
import { LocaleContext } from "../../../src/i18n/context";
export const frontmatter = {
  title: "Dream 다운로드",
  description: "macOS, Windows, Linux용 Dream을 다운로드하세요.",
  search: false,
};
export default function LocalizedPage() {
  return (
    <LocaleContext.Provider value="ko">
      <Page />
    </LocaleContext.Provider>
  );
}
