// Generated by scripts/generate-locales.mjs.
import Page from "../home";
import { LocaleContext } from "../../../src/i18n/context";
export const frontmatter = {
  title: "Dream — AI 코딩을 위한 IDE",
  description:
    "Dream은 여러 AI 코딩 에이전트와 함께 작업할 수 있는 오픈 소스 데스크톱 IDE입니다.",
  search: false,
};
export default function LocalizedPage() {
  return (
    <LocaleContext.Provider value="ko">
      <Page />
    </LocaleContext.Provider>
  );
}
