// Generated by scripts/generate-locales.mjs.
export { default } from "../download";
export const frontmatter = {
  title: "下载 Dream",
  description: "下载适用于 macOS、Windows 和 Linux 的 Dream。",
  search: false,
};
