// Generated by scripts/generate-locales.mjs.
import Page from "../download";
import { LocaleContext } from "../../../src/i18n/context";
export const frontmatter = {
  title: "下载 Dream",
  description: "下载适用于 macOS、Windows 和 Linux 的 Dream。",
  search: false,
};
export default function LocalizedPage() {
  return (
    <LocaleContext.Provider value="zh-Hans">
      <Page />
    </LocaleContext.Provider>
  );
}
