// Generated by scripts/generate-locales.mjs.
import Page from "../home";
import { LocaleContext } from "../../../src/i18n/context";
export const frontmatter = {
  title: "Dream — 专为 AI 编程打造的 IDE",
  description: "Dream 是一款开源桌面 IDE，让你与多个 AI 编程智能体协同工作。",
  search: false,
};
export default function LocalizedPage() {
  return (
    <LocaleContext.Provider value="zh-Hans">
      <Page />
    </LocaleContext.Provider>
  );
}
