// Public shiso.config.ts translation keys for languages Shiso does not bundle.
// Values are the existing source strings in Dream's translation catalogs.
export const shisoLabels = {
  menu: "Menu",
  documentationNavigation: "Documentation navigation",
  sections: "Sections",
  tableOfContents: "On this page",
  tableOfContentsNavigation: "Table of contents",
  searchTitle: "Search",
  searching: "Searching...",
  searchUnavailable: "Search unavailable",
  noResults: "No results",
  lastUpdated: "Last updated on",
  relatedTopics: "Related topics",
  previousPage: "Previous",
  nextPage: "Next",
  notFound: "Page not found",
  dismissBanner: "Dismiss banner",
  toggleTheme: "Toggle theme",
  moreOptions: "More options",
  copied: "Copied",
  expand: "Expand",
  collapse: "Collapse",
  copyPage: "Copy page",
  copyPageDescription: "Copy this page as Markdown",
  viewMarkdown: "View as Markdown",
  viewMarkdownDescription: "Open this page as plain Markdown",
  openInChatGPT: "Open in ChatGPT",
  openInClaude: "Open in Claude",
  openInPerplexity: "Open in Perplexity",
  askQuestionsAboutPage: "Ask questions about this page",
  searchPlaceholder: "Search documentation...",
  poweredBy: "Powered by",
  close: "Close",
  copyCode: "Copy code",
  viewImage: "Zoom image",
  fullSizeImage: "Zoom image",
};
