// Generated by scripts/generate-locales.mjs.
export { default } from "../download";
export const frontmatter = {
  title: "Télécharger Dream",
  description: "Téléchargez Dream pour macOS, Windows et Linux.",
  search: false,
};
