// Generated by scripts/generate-locales.mjs.
import Page from "../download";
import { LocaleContext } from "../../../src/i18n/context";
export const frontmatter = {
  title: "Télécharger Dream",
  description: "Téléchargez Dream pour macOS, Windows et Linux.",
  search: false,
};
export default function LocalizedPage() {
  return (
    <LocaleContext.Provider value="fr">
      <Page />
    </LocaleContext.Provider>
  );
}
