// Generated by scripts/generate-locales.mjs.
import Page from "../hello";
import { LocaleContext } from "../../../src/i18n/context";
export const frontmatter = {
  title: "Dream — l’IDE pour coder avec l’IA",
  description:
    "Dream est un IDE de bureau open source pour travailler avec plusieurs agents de programmation IA.",
  search: false,
};
export default function LocalizedPage() {
  return (
    <LocaleContext.Provider value="fr">
      <Page />
    </LocaleContext.Provider>
  );
}
