// Generated by scripts/generate-locales.mjs.
export { default } from "../home";
export const frontmatter = {
  title: "Dream — l’IDE pour coder avec l’IA",
  description:
    "Dream est un IDE de bureau open source pour travailler avec plusieurs agents de programmation IA.",
  search: false,
};
