// Generated by scripts/generate-locales.mjs.
import Page from "../download";
import { LocaleContext } from "../../../src/i18n/context";
export const frontmatter = {
  title: "Scarica Dream",
  description: "Scarica Dream per macOS, Windows e Linux.",
  search: false,
};
export default function LocalizedPage() {
  return (
    <LocaleContext.Provider value="it">
      <Page />
    </LocaleContext.Provider>
  );
}
