// Generated by scripts/generate-locales.mjs.
export { default } from "../download";
export const frontmatter = {
  title: "Scarica Dream",
  description: "Scarica Dream per macOS, Windows e Linux.",
  search: false,
};
