// Generated by scripts/generate-locales.mjs.
export { default } from "../hello";
export const frontmatter = {
  title: "Dream — l’IDE per programmare con l’IA",
  description:
    "Dream è un IDE desktop open source per lavorare con più agenti di programmazione IA.",
  search: false,
};
