// Generated by scripts/generate-locales.mjs.
import Page from "../hello";
import { LocaleContext } from "../../../src/i18n/context";
export const frontmatter = {
  title: "Dream — l’IDE per programmare con l’IA",
  description:
    "Dream è un IDE desktop open source per lavorare con più agenti di programmazione IA.",
  search: false,
};
export default function LocalizedPage() {
  return (
    <LocaleContext.Provider value="it">
      <Page />
    </LocaleContext.Provider>
  );
}
