// Generated by scripts/generate-locales.mjs.
export { default } from "../download";
export const frontmatter = {
  title: "Descargar Dream",
  description: "Descarga Dream para macOS, Windows y Linux.",
  search: false,
};
