// Generated by scripts/generate-locales.mjs.
import Page from "../download";
import { LocaleContext } from "../../../src/i18n/context";
export const frontmatter = {
  title: "Descargar Dream",
  description: "Descarga Dream para macOS, Windows y Linux.",
  search: false,
};
export default function LocalizedPage() {
  return (
    <LocaleContext.Provider value="es">
      <Page />
    </LocaleContext.Provider>
  );
}
