// Generated by scripts/generate-locales.mjs.
export { default } from "../hello";
export const frontmatter = {
  title: "Dream — el IDE para programar con IA",
  description:
    "Dream es un IDE de escritorio de código abierto para trabajar con varios agentes de programación con IA.",
  search: false,
};
