// Generated by scripts/generate-locales.mjs.
import Page from "../home";
import { LocaleContext } from "../../../src/i18n/context";
export const frontmatter = {
  title: "Dream — el IDE para programar con IA",
  description:
    "Dream es un IDE de escritorio de código abierto para trabajar con varios agentes de programación con IA.",
  search: false,
};
export default function LocalizedPage() {
  return (
    <LocaleContext.Provider value="es">
      <Page />
    </LocaleContext.Provider>
  );
}
